"""Liquidity-conditioned residual imbalance research tools."""

from lcri_lab.absorption import add_shadow_absorption
from lcri_lab.baseline import LiquidityBaseline, compute_lcri, design_feature_names
from lcri_lab.evaluation import (
    absorption_regime_metrics,
    calibration_curve,
    compare_transmission_signal,
    evaluate_cost_aware_signals,
    evaluate_signals,
    feature_stability_report,
    generalization_overview,
    lcri_generalization_blocker_summary,
    lcri_generalization_critical_contexts,
    lcri_generalization_gap_leaderboard,
    lcri_generalization_gate_decision,
    lcri_generalization_scope_gate_decisions,
    lcri_generalization_scope_risk,
    lcri_generalization_scope_summary,
    lcri_generalization_severity_by_scope,
    lcri_generalization_severity,
    lcri_generalization_severity_summary,
    lcri_gap_delta_flags,
    lcri_gap_delta_scorecard,
    lcri_worst_generalization_context,
    lcri_gap_delta_summary,
    lcri_generalization_gap_delta,
    lcri_tail_diagnostics,
    regime_generalization_gap,
    regime_metrics,
    signal_generalization_gap,
    summarize_signal_lift,
    transition_conditioned_metrics,
    transition_generalization_gap,
    transition_robustness_summary,
    transition_signal_lift,
)
from lcri_lab.features import (
    add_regime_transition_features,
    compute_features,
    tag_liquidity_regimes,
)
from lcri_lab.labels import add_transaction_cost_labels
from lcri_lab.memory import add_pressure_memory
from lcri_lab.model import ARTIFACT_VERSION, LCRIModel, ModelConfig
from lcri_lab.publishability import PublishabilityConfig, add_publishability_gate
from lcri_lab.reversal import add_queue_reversal_risk
from lcri_lab.schema import snapshot_required_columns
from lcri_lab.sensitivity import publishability_latency_sweep
from lcri_lab.simulator import SimulationConfig, simulate_order_books

__all__ = [
    "ARTIFACT_VERSION",
    "absorption_regime_metrics",
    "add_transaction_cost_labels",
    "add_pressure_memory",
    "add_regime_transition_features",
    "add_shadow_absorption",
    "add_publishability_gate",
    "add_queue_reversal_risk",
    "LCRIModel",
    "LiquidityBaseline",
    "ModelConfig",
    "PublishabilityConfig",
    "publishability_latency_sweep",
    "SimulationConfig",
    "calibration_curve",
    "compare_transmission_signal",
    "compute_features",
    "compute_lcri",
    "design_feature_names",
    "evaluate_cost_aware_signals",
    "evaluate_signals",
    "feature_stability_report",
    "generalization_overview",
    "lcri_generalization_blocker_summary",
    "lcri_generalization_critical_contexts",
    "lcri_generalization_gap_leaderboard",
    "lcri_generalization_gate_decision",
    "lcri_generalization_scope_gate_decisions",
    "lcri_generalization_scope_risk",
    "lcri_generalization_scope_summary",
    "lcri_generalization_severity_by_scope",
    "lcri_generalization_severity",
    "lcri_generalization_severity_summary",
    "lcri_gap_delta_flags",
    "lcri_gap_delta_scorecard",
    "lcri_worst_generalization_context",
    "lcri_gap_delta_summary",
    "lcri_generalization_gap_delta",
    "lcri_tail_diagnostics",
    "regime_generalization_gap",
    "regime_metrics",
    "signal_generalization_gap",
    "summarize_signal_lift",
    "tag_liquidity_regimes",
    "transition_conditioned_metrics",
    "transition_generalization_gap",
    "transition_robustness_summary",
    "transition_signal_lift",
    "simulate_order_books",
    "snapshot_required_columns",
]
